### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by lovellfelix** [grabbou/atom-xcode#4]
**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-xcode](https://github.com/grabbou/atom-xcode) package, v0.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/.../.atom/packages/atom-xcode/lib/ui/bottom-panel.js:82

TypeError: Cannot read property 'name' of undefined
    at xcatom-bottom-panel.runProject (/Users/../.atom/packages/atom-xcode/lib/ui/bottom-panel.js:82:54)
    at xcatom-bottom-panel-action.handler (/Users/../.atom/packages/atom-xcode/lib/ui/bottom-panel.js:46:27)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "followSymlinks": true
  }
}
```
### Installed Packages

``` coffee

# Dev
No dev packages
```

**Comment by pharapeti** [comment]
I can replicate this issue.

**Comment by radko93** [comment]
This library is no longer supported @pharapeti
