### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Solxvn** [grabbou/atom-xcode#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [atom-xcode](https://github.com/grabbou/atom-xcode) package 0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'find' of undefined

```
At /Users/skyos/.atom/packages/atom-xcode/lib/ui/selected-simulator.js:47

TypeError: Cannot read property 'find' of undefined
    at HTMLElement.getSelectedItem (/packages/atom-xcode/lib/ui/selected-simulator.js:47:16)
    at HTMLElement.runProject (/packages/atom-xcode/lib/ui/bottom-panel.js:80:46)
    at HTMLElement.handler (/packages/atom-xcode/lib/ui/bottom-panel.js:46:27)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
advanced-open-file 0.16.7 
atom-beautify 0.30.6 
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.5.3 
atom-prettify 0.1.3 
atom-react-native-style 0.2.0 
atom-xcode 0.1.3 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
native-color-picker 0.2.5 
prettier-atom 0.40.0 
react-es6-snippets 0.3.0 
react-native-components 0.1.1 
react-native-redux-snippets-es6-es7-atom 0.6.0 
react-native-snippets 0.3.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
tree-view-open-files 0.3.0 
```

**Comment by pharapeti** [comment]
I can also replicate this issue.
